spring.application.name=comfort-index

spring.config.import=optional:file:.env[.properties]
openweathermap.api.key=${OPENWEATHERMAP_API_KEY}

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-5esopfh3mi6fzoxo.us.auth0.com/
auth0.audience=https://comfort-index-api